/* 
 * File:   CCP1_CFG.h
 * Author: smart
 *
 * Created on 27 ?????, 2024, 03:47 ?
 */

#ifndef CCP1_CFG_H
#define	CCP1_CFG_H

#define CCP_CFG_CAPTURE_MODE_SELECTED 0X00
#define CCP_CFG_COMPARE_MODE_SELECTED 0X01
#define CCP_CFG_PWM_MODE_SELECTED     0X02

#define CCP1_CFG_SELECTED_MODE (CCP_CFG_PWM_MODE_SELECTED) 
#define CCP2_CFG_SELECTED_MODE (CCP_CFG_CAPTURE_MODE_SELECTED) 


#endif	/* CCP1_CFG_H */

